-- 코드를 입력하세요
SELECT PRODUCT_CODE, SUM(SALES_AMOUNT*PRICE) as SALES
FROM PRODUCT  pro
JOIN OFFLINE_SALE  os on pro.PRODUCT_ID = os.PRODUCT_ID 
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC