-- 코드를 입력하세요
SELECT BOOK_ID, AUTHOR_NAME, TO_CHAR(PUBLISHED_DATE, 'yyyy-mm-dd') as PUBLISHED_DATE
FROM BOOK 
LEFT JOIN AUTHOR on BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
WHERE CATEGORY = '경제'
ORDER BY PUBLISHED_DATE ASC

-- WHERE절에 해당하는 것만 빼고 JOIN실시
SELECT BOOK_ID, AUTHOR_NAME, PUBLISHED_DATE
FROM (
    SELECT BOOK_ID, AUTHOR_ID, TO_CHAR(PUBLISHED_DATE, 'yyyy-mm-dd') as PUBLISHED_DATE
    FROM BOOK 
    WHERE CATEGORY = '경제'
    ) t
LEFT JOIN AUTHOR on t.AUTHOR_ID = AUTHOR.AUTHOR_ID
ORDER BY PUBLISHED_DATE ASC
